import React from 'react';
import { Modal } from 'antd';
// import QRCode from 'qrcode.react';import QRCode from 'qrcode.react';
// import QRCode from 'qrcode.react';
// import QRCode from "qrcode";
import { QRCodeSVG } from 'qrcode.react';
import './InvoiceModal.css'; // Import your regular CSS

const InvoiceModalPremium = ({ open, onCancel }) => {
  return (
    <Modal
      open={open}
      onCancel={onCancel}
      footer={null}
      // width={800}
      closeIcon={false}
       className="custom-invoice-modal" // Add a custom class
      bodyStyle={{ padding: 0 }} // Remove default body padding
    //   style={{ padding: 0,  top: 20, background:'red'  }}
     
    >
      <div className="invoice-container">
        <div className="invoice-header">Invoice</div>

        <div className="invoice-top">
          <img src="/monaHeaderLogo.svg" alt="Logo" className="invoice-logos" />
          <div className="invoice-infors">
            <h5>Premium Report</h5>
            <div>Mona Technologies Limited</div>
            <div>613 Ahmadu Bello Way, Abuja</div>
            <div>+234 903 345 6789</div>
            <div>info@monaprotect.com</div>
          </div>
        </div>

        <div className="invoice-meta i_m_2">
            <div ><div className='strongP'>Report ID:</div> RPT123456</div>
            <div><div className='strongP'>Generated by:</div> Admin 1/Michael James</div>
            <div><div className='strongP'>Generated on:</div> 2025–01–15 16:09:05</div>
            <div><div className='strongP'>Version:</div> 1.0</div>
            <div><div className='strongP'>Date Range:</div> Apr 1-Jun 30 2025</div>
          
        </div>
<hr />
        <div className="invoice-section">
          <h5>Overview</h5>
          <div>Total No. of Devices: <strong>10</strong></div>
          <div>Total Premium: <strong>#100,000</strong></div>
          <div>Total Sum Insured:: <strong>#200,000</strong></div>
        </div>
<hr />
        <div className="invoice-table-section">
          <h5>Premium Information</h5>
          <table className="invoice-table invoice-table-2">
            <thead>
              <tr>
                <th>Device ID</th>
                <th>Brand</th>
                <th>Model</th>
                <th>IMEI</th>
                <th>Total Sum Insured</th>
                <th>Premium</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>#0001</td>
                <td>Samsung</td>
                <td>Galaxy S20</td>
                <td>356789123456789</td>
                <td>#723,345</td>
                <td>#723,345</td>
                <td>2025-01-15</td>
                
              </tr>
              <tr>
                <td>#0002</td>
                <td>Samsung</td>
                <td>Galaxy S20</td>
                <td>356789123456789</td>
                <td>#723,345</td>
                <td>#723,345</td>
                <td>2025-01-15</td>
              </tr>
            </tbody>
          </table>
        </div>

   
<hr />
        <div className="invoice-bottom">
          Generated on: 2025–01–15 16:30 | Page 1 of 1 | Report ID: RPT123456 | Mona Protect<br />
          <span className="confidential">Confidential – For internal use only</span>
        </div>
      </div>
    </Modal>
  );
};

export default InvoiceModalPremium;
