import React from 'react';
import { Modal } from 'antd';
import { CloseOutlined } from '@ant-design/icons';
// import QRCode from 'qrcode.react';import QRCode from 'qrcode.react';
// import QRCode from 'qrcode.react';
// import QRCode from "qrcode";
import { QRCodeSVG } from 'qrcode.react';
import './InvoiceModal.css'; // Import your regular CSS

const InvoiceModal = ({ open, onCancel }) => {
  return (
    <Modal
      open={open}
      onCancel={onCancel}
      footer={null}
      width={800}
      closeIcon={<CloseOutlined />}
    //   style={{ padding: 0,  top: 20, background:'red'  }}
     
    >
      <div className="invoice-container">
        <div className="invoice-header">Invoice</div>

        <div className="invoice-top">
          <img src="/monaprotect-logo.png" alt="Logo" className="invoice-logo" />
          <div className="invoice-info">
            <h2>Invoice</h2>
            <p>Mona Technologies Limited</p>
            <p>613 Ahmadu Bello Way, Abuja</p>
            <p>+234 903 345 6789</p>
            <p>info@monaprotect.com</p>
          </div>
        </div>

        <div className="invoice-meta">
          <div>
            <p><strong>Report ID:</strong> RPT123456</p>
            <p><strong>Generated by:</strong> Admin 1/Michael James</p>
            <p><strong>Generated on:</strong> 2025–01–15 16:09:05</p>
            <p><strong>Version:</strong> 1.0</p>
          </div>
        </div>

        <div className="invoice-section">
          <h3>Overview</h3>
          <p>Total No. of Claims: <strong>10</strong></p>
          <p>Total Payout Amount: <strong>#100,000</strong></p>
        </div>

        <div className="invoice-table-section">
          <h3>Highlight of the Issue</h3>
          <table className="invoice-table">
            <thead>
              <tr>
                <th>S/N</th>
                <th>Issues</th>
                <th>Count</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>01</td>
                <td>Lorem ipsum dolor sit amet</td>
                <td>5</td>
              </tr>
              <tr>
                <td>02</td>
                <td>Lorem ipsum dolor sit amet</td>
                <td>5</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="invoice-table-section">
          <h3>Claims Information</h3>
          <table className="invoice-table">
            <thead>
              <tr>
                <th>Claim ID</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Sum Insured Balance</th>
                <th>Claim Amount</th>
                <th>Approved by</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>#0001</td>
                <td>Samsung</td>
                <td>Galaxy S20</td>
                <td>#723,345</td>
                <td>#123,345</td>
                <td>Admin 1</td>
                <td>2025–01–15</td>
              </tr>
              <tr>
                <td>#0001</td>
                <td>Samsung</td>
                <td>Galaxy S20</td>
                <td>#723,345</td>
                <td>#123,345</td>
                <td>Admin 1</td>
                <td>2025–01–15</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="invoice-footer">
          <div className="invoice-payment-details">
            <h3>Payment Details</h3>
            <p>Please remit payment to the following account:</p>
            <p><strong>Account Name:</strong> Mona Protect Limited</p>
            <p><strong>Bank Name:</strong> Commonwealth Bank</p>
            <p><strong>Acc #:</strong> 12345678</p>
            <p><strong>Payment Due Date:</strong> 2024–02–01</p>
          </div>
          <div className="invoice-qr">
            <p><strong>QR Code payment</strong></p>
            <QRCodeSVG value="https://monaprotect.com/payment-details" size={80} />
            <p className="qr-note">Scan to verify payment details</p>
          </div>
        </div>

        <div className="invoice-bottom">
          Generated on: 2025–01–15 16:30 | Page 1 of 1 | Report ID: RPT123456 | Mona Protect<br />
          <span className="confidential">Confidential – For internal use only</span>
        </div>
      </div>
    </Modal>
  );
};

export default InvoiceModal;
